# Generated by Django 3.1.2 on 2020-10-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='status',
            field=models.CharField(default='available', max_length=100),
        ),
    ]
